files:
  - source: /composeApp/src/commonMain/composeResources/values/strings.xml
    translation: /composeApp/src/commonMain/composeResources/values-%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
