#!/usr/bin/env python3

import json
import os
import sys

# Ordered list of all parameters accepted by lightColorScheme / darkColorScheme,
# matching the signature provided.
COLOR_SCHEME_PARAMS = [
    "primary",
    "onPrimary",
    "primaryContainer",
    "onPrimaryContainer",
    "inversePrimary",
    "secondary",
    "onSecondary",
    "secondaryContainer",
    "onSecondaryContainer",
    "tertiary",
    "onTertiary",
    "tertiaryContainer",
    "onTertiaryContainer",
    "background",
    "onBackground",
    "surface",
    "onSurface",
    "surfaceVariant",
    "onSurfaceVariant",
    "surfaceTint",
    "inverseSurface",
    "inverseOnSurface",
    "error",
    "onError",
    "errorContainer",
    "onErrorContainer",
    "outline",
    "outlineVariant",
    "scrim",
    "surfaceBright",
    "surfaceContainer",
    "surfaceContainerHigh",
    "surfaceContainerHighest",
    "surfaceContainerLow",
    "surfaceContainerLowest",
    "surfaceDim",
    "primaryFixed",
    "primaryFixedDim",
    "onPrimaryFixed",
    "onPrimaryFixedVariant",
    "secondaryFixed",
    "secondaryFixedDim",
    "onSecondaryFixed",
    "onSecondaryFixedVariant",
    "tertiaryFixed",
    "tertiaryFixedDim",
    "onTertiaryFixed",
    "onTertiaryFixedVariant",
]

# Maps ThemeVariants interface property names → JSON scheme keys
VARIANT_MAP = {
    "light":               "light",
    "dark":                "dark",
    "lightHighContrast":   "light-high-contrast",
    "lightMediumContrast": "light-medium-contrast",
    "darkHighContrast":    "dark-high-contrast",
    "darkMediumContrast":  "dark-medium-contrast",
}

# Which variants use lightColorScheme vs darkColorScheme
DARK_VARIANTS = {"dark", "darkHighContrast", "darkMediumContrast"}


def hex_to_kotlin_color(hex_color: str) -> str:
    """Convert '#RRGGBB' or '#AARRGGBB' to 'Color(0xFFRRGGBB)'."""
    h = hex_color.lstrip("#")
    if len(h) == 6:
        # No alpha → assume fully opaque
        return f"Color(0xFF{h.upper()})"
    elif len(h) == 8:
        return f"Color(0x{h.upper()})"
    else:
        raise ValueError(f"Unexpected hex color format: '{hex_color}'")


def seed_to_class_name(seed: str) -> str:
    """
    Convert a seed hex string like '#4385F6' to a valid Kotlin class name
    suffix, e.g. 'Theme4385F6'.
    """
    clean = seed.lstrip("#").upper()
    return f"Theme{clean}"


def build_color_scheme_block(scheme_data: dict, variant_name: str, indent: str = "    ") -> str:
    """
    Build the body of a lightColorScheme(...) or darkColorScheme(...) call.
    Missing keys produce a comment so the developer can fill them in.
    """
    fn = "darkColorScheme" if variant_name in DARK_VARIANTS else "lightColorScheme"
    lines = [f"{fn}("]
    inner = indent + "    "
    for param in COLOR_SCHEME_PARAMS:
        if param in scheme_data:
            color_val = hex_to_kotlin_color(scheme_data[param])
            lines.append(f"{inner}{param} = {color_val},")
        else:
            lines.append(f"{inner}// {param} not found in JSON")
    lines.append(f"{indent})")
    return f"\n{inner}".join([""])  # reset; rebuild properly below

def build_color_scheme_call(scheme_data: dict, variant_name: str, indent: str = "    ") -> str:
    fn = "darkColorScheme" if variant_name in DARK_VARIANTS else "lightColorScheme"
    inner_indent = indent + "    "
    param_lines = []
    for param in COLOR_SCHEME_PARAMS:
        if param in scheme_data:
            color_val = hex_to_kotlin_color(scheme_data[param])
            param_lines.append(f"{inner_indent}{param} = {color_val},")
        else:
            param_lines.append(f"{inner_indent}// {param} not found in JSON")
    params_str = "\n".join(param_lines)
    return f"{fn}(\n{params_str}\n{indent})"


def generate_kotlin(theme_json: dict) -> str:
    seed: str = theme_json.get("seed", "#000000")
    schemes: dict = theme_json.get("schemes", {})
    class_name = seed_to_class_name(seed)
    # Use the seed stripped of '#' as the display name
    display_name = seed.lstrip("#").upper()

    lines = []

    # File header
    lines.append("// Auto-generated by theme-generator.py")
    lines.append(f"// Seed color: {seed}")
    lines.append("")
    lines.append("package com.arn.scrobble.themes.colors")
    lines.append("")
    lines.append("import androidx.compose.material3.darkColorScheme")
    lines.append("import androidx.compose.material3.lightColorScheme")
    lines.append("import androidx.compose.ui.graphics.Color")
    lines.append("")

    # Object declaration
    lines.append(f"object {class_name} : ThemeVariants {{")
    lines.append("")

    # name property
    lines.append(f'    override val name = "{display_name}"')
    lines.append("")

    # One override property per variant
    for prop_name, json_key in VARIANT_MAP.items():
        scheme_data = schemes.get(json_key)
        if scheme_data is None:
            lines.append(f"    // Scheme '{json_key}' not found in JSON")
            lines.append(f"    override val {prop_name}: ColorScheme")
            lines.append(f"        get() = TODO(\"Scheme '{json_key}' missing from theme JSON\")")
            lines.append("")
            continue

        call = build_color_scheme_call(scheme_data, prop_name, indent="        ")
        lines.append(f"    override val {prop_name} get() =")
        lines.append(f"        {call}")
        lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: theme-generator.py <input/path/to/material-theme.json> <output/path/to/kotlin/themes/dir>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_dir = sys.argv[2]

    if not os.path.isfile(input_path):
        print(f"Error: input file not found: {input_path}")
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        theme_json = json.load(f)

    seed: str = theme_json.get("seed", "#000000")
    class_name = seed_to_class_name(seed)
    output_filename = f"{class_name}.kt"
    output_path = os.path.join(output_dir, output_filename)

    kotlin_source = generate_kotlin(theme_json)

    os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(kotlin_source)

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()